### ISSUE TITLE
NULL is not Subtype of Future<OrString>

### ISSUE THREAD

**Issue by ShakeelKhalid1913** [arshmancodes/paymob_pakistan#1]
I just want to know how can I get response from iframe programmatically. kindly help

![image](https://github.com/arshmancodes/paymob_pakistan/assets/93911372/087d59fd-156d-475f-b9d4-ca675670bc9c)

**Comment by arshmancodes** [comment]
Below is the code to perform the payment using the Paymob Pakistan Plugin,
Make sure to initialize before performing the Payment Request and you will get the response from the iFrame in the onPayment function  as PaymobResponse type.

```
final PaymobResponse? response = await PaymobPakistan.instance.pay(
  context: context,
  currency: "PKR",
  paymentType: PaymentType.card, // or you can User paymentType: PaymentType.jazzcash OR PaymentType.easypaisa
  amountInCents: "50000", // 500 PKR
  onPayment: (response) => setState(() => this.response = response), // Optional
)
```

PS: Can you show me the code how are you trying to perform the request. Make sure to remove your keys before posting over here.

**Comment by ShakeelKhalid1913** [comment]
Haha.. I don't know what happened. it's working now. Thank you for your time and I really think it is a great flutter library. 
I just want to know (out of scope) 

I'm only getting this type. how can I add jazcash and easypaisa.
![image](https://github.com/arshmancodes/paymob_pakistan/assets/93911372/82add14b-7c27-4706-84e6-250d0a3dc045)
 
secondly how can I receive transaction payments from Paymob to my personal account?

**Comment by arshmancodes** [comment]
Contact Paymob to approve your account and Make it LIVE, When your account will be live you will see the Integration ID's of Jazzcash and Easypaisa in your paymob console, Just add those Integration ID's while initializing the PaymobPakistan Object.

Then you can use the parameter PaymentType to PaymentType.jazzcash for Jazzcash and PaymentType.easypaisa for Easypaisa.

If you have any other queries let me know otherwise i'll close this issue.

**Comment by ShakeelKhalid1913** [comment]
Alright Thank you
